apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-meet-torture
spec:
  selector:
    matchLabels:
      app: jitsi-meet-torture
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxSurge: 1
     maxUnavailable: 0
  template:
    metadata:
      labels:
        app: jitsi-meet-torture
    spec:
      containers:
      - name: jitsi-meet-torture
        image: 718762496685.dkr.ecr.ap-south-1.amazonaws.com/sariska/automation-service:latest 
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"