apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-node-chrome-rep
  namespace: automation
spec:  
  replicas: 1
  selector:
    app: selenium-node-chrome
  template:
    metadata:
      name: selenium-node-chrome
      labels:
        app: selenium-node-chrome
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: "managed-ng-automation" 
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome:3.141.59-20210929
          resources:
            limits:
              memory: "2Gi"
          # command: ['sh', '-c', 'sudo mkdir resources; sudo wget -O resources/FourPeople_1280x720_60.y4m https://media.xiph.org/video/derf/y4m/FourPeople_1280x720_60.y4m; while true; do sleep 30; done;']
          ports:
            - containerPort: 5555
          env:
           - name:  HUB_HOST
             value: "selenium-srv" 
           - name: HUB_PORT
             value: "4444"
           - name: SE_EVENT_BUS_HOST
             value: "selenium-srv"
           - name: SE_EVENT_BUS_PUBLISH_PORT
             value: "4442"
           - name: SE_EVENT_BUS_SUBSCRIBE_PORT
             value: "4443"
           - name: JAVA_OPTS
             value: "-Dwebdriver.chrome.whitelistedIps="
          volumeMounts:
            - name: automation-pvc
              mountPath: /usr/share/jitsi-meet-torture/resources
      volumes:
        - name: automation-pvc
          persistentVolumeClaim:
            claimName: asset-pvc