apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-node-chrome-rep
  namespace: automation
spec:  
  replicas: 3
  selector:
    app: selenium-node-chrome
  template:
    metadata:
      name: selenium-node-chrome
      labels:
        app: selenium-node-chrome
    spec:
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: "managed-ng-automation" 
      containers:
        - name: selenium-node-chrome
          image: selenium/node-chrome:3.141.59-20200409
          ports:
            - containerPort: 5555
          env:
           - name:  HUB_HOST
             value: "selenium-srv" 
           - name: HUB_PORT
             value: "4444"
           - name: SE_EVENT_BUS_HOST
             value: "selenium-srv"
           - name: SE_EVENT_BUS_PUBLISH_PORT
             value: "4442"
           - name: SE_EVENT_BUS_SUBSCRIBE_PORT
             value: "4443"
           - name: JAVA_OPTS
             value: "-Dwebdriver.chrome.whitelistedIps="