From selenium/node-chrome:3.141.59-20210929

USER root

RUN mkdir -p /usr/share/jitsi-meet-torture/resources

COPY ./fakeAudioStream.wav /usr/share/jitsi-meet-torture/resources
COPY ./fakeVideoStream.y4m /usr/share/jitsi-meet-torture/resources