From selenium/node-firefox

USER root

RUN mkdir -p /usr/share/jitsi-meet-torture/resources

COPY ./fakeAudioStream.wav /usr/share/jitsi-meet-torture/resources
COPY ./fakeVideoStream.y4m /usr/share/jitsi-meet-torture/resources